spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html; charset=utf-8
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/contract?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
mail:
  smtp:
    auth: true
    port: 465
    timeout: 5000
  mail:
    transport:
      protocol:smtp
  send:
    charset: UTF-8
  is:
    ssl: true
  #host: smtp.126.com
  host: smtp.qq.com
  auth:
    name: 1305840202@qq.com
    password: rsqsvuxaoxvoibgf
    #name: goodlook0123@126.com
    #password: dong#$123321
